name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "dnf.spec"
        
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp-upload.net
        user: fl0te_27750748
        password: gd2cvycn
        localDir: ${{ steps.rpm.outputs.rpm_dir_path }}
        remoteDir: "repos.hostfree2021.ml/centos/packages/d/dnf"
